import {describe,it,expect} from 'vitest';
import {generate,skills,validateProblem,buildScaffold,fresh,validateSave,SaveService,MasteryService,SessionService,MathEngine,stats,migrateSave,type Attempt} from '../src/core';
import {levels} from '../src/levels';
const store=()=>new SaveService();
let evidenceOrdinal=0;
function attempt(overrides:Partial<Attempt>={}):Attempt{const n=evidenceOrdinal++%6;return {id:crypto.randomUUID(),sessionId:'day1',time:Date.now(),skillId:'N0',family:`0:${n}:${n}`,templateId:'N0-1',seed:n,prompt:'How many beads?',answer:n,firstResponse:n,firstTryCorrect:true,hint:false,scaffoldDepth:0,latencyMs:2300,representation:'visual',context:'practice',...overrides};}
describe('seeded mathematics',()=>{
 for(const skill of skills)it(`${skill.id}: 1500 generated items and scaffold paths are valid`,()=>{const layouts=new Set();for(let seed=0;seed<1500;seed++){const p=generate(skill.id,seed);expect(validateProblem(p)).toBe(true);expect(generate(skill.id,seed)).toEqual(p);expect(buildScaffold(p).at(-1)?.answer).toBe(p.answer);expect(buildScaffold(p).every(s=>s.answer>=0&&s.answer<=20)).toBe(true);layouts.add(p.layout);}expect(layouts.size).toBe(4);});
 it('generates 13 minus 5 and provides a correct take-away scaffold',()=>{const p=Array.from({length:10000},(_,i)=>generate('S5',i)).find(p=>p.a===13&&p.b===5)!;expect(p).toBeTruthy();expect(p.answer).toBe(8);expect(p.prompt).toBe('13 − 5 = ?');expect(buildScaffold(p).map(s=>s.answer)).toEqual([13,5,8,8]);});
});
describe('mastery evidence',()=>{
 it('keeps an independent wrong first answer in accuracy after guided correction',()=>{const s=store(),m=new MasteryService(s);m.record(attempt({initialIndependent:true}));m.record(attempt({initialIndependent:true,firstResponse:2,firstTryCorrect:false,hint:true,scaffoldDepth:4,latencyMs:null}));expect(stats(s.data,'N0').independentAccuracy).toBe(.5);});
 it('requires at least two sessions',()=>{const s=store(),m=new MasteryService(s);for(let i=0;i<20;i++)m.record(attempt());expect(s.data.progress.N0.consolidated).toBe(false);for(let i=0;i<5;i++)m.record(attempt({sessionId:'day2'}));expect(s.data.progress.N0.consolidated).toBe(true);expect(m.current()).toBe('N1');});
 it('assisted work cannot manufacture independent mastery',()=>{const s=store(),m=new MasteryService(s);for(let i=0;i<30;i++)m.record(attempt({sessionId:`day${i%3}`,hint:true,scaffoldDepth:4,firstTryCorrect:false,latencyMs:null}));expect(s.data.progress.N0.consolidated).toBe(false);expect(stats(s.data,'N0').independent.length).toBe(0);});
 it('slow accurate answers consolidate but do not become fluent',()=>{const s=store(),m=new MasteryService(s);for(let i=0;i<30;i++)m.record(attempt({sessionId:`day${i%3}`,latencyMs:12000}));expect(s.data.progress.N0.consolidated).toBe(true);expect(s.data.progress.N0.fluent).toBe(false);m.record(attempt({firstTryCorrect:false,hint:true,scaffoldDepth:4}));expect(s.data.progress.N0.consolidated).toBe(true);});
 it('fluent requires 3 sessions and review advances only when due',()=>{const s=store(),m=new MasteryService(s);for(let i=0;i<30;i++)m.record(attempt({sessionId:`day${i%3}`}));expect(s.data.progress.N0.fluent).toBe(true);s.data.progress.N0.due=0;const before=s.data.progress.N0.interval;m.record(attempt());expect(s.data.progress.N0.interval).toBe(before+1);});
 it('duplicate responses do not duplicate attempt records',()=>{const s=store(),m=new MasteryService(s),a=attempt();m.record(a);m.record(a);expect(s.data.attempts.length).toBe(1);});
});
describe('save and reward transactions',()=>{
 it('validates new and active saves',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));expect(validateSave(s.data)).toBe(true);session.start(0);expect(validateSave(s.data)).toBe(true);});
 it('refuses malformed and future saves without replacing state',()=>{const s=store(),old=s.data;expect(()=>s.import('{"schemaVersion":100}')).toThrow();expect(s.data).toBe(old);expect(validateSave({...fresh(),settings:{}})).toBe(false);});
 it('does not duplicate pickups, rescues or bracelet rewards',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));session.start(0);const bead=levels[0].beads[0];session.collect(bead.id);session.collect(bead.id);expect(s.data.active!.beads).toEqual([bead.color]);session.rescue();session.rescue();expect(s.data.rescued).toHaveLength(1);expect(s.data.active!.beads).toEqual([bead.color]);s.data.active!.design=[0];session.finishBracelet('My magic');session.finishBracelet('My magic');expect(s.data.bracelets).toHaveLength(1);expect(validateSave(s.data)).toBe(true);});
 it('new session starts after inactivity, not every reload',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));const first=s.data.session.id;session.beginSession();expect(s.data.session.id).toBe(first);s.data.session.last-=31*60000;session.beginSession();expect(s.data.session.newFamilies).toHaveLength(0);});
});

describe('v0.2 inventory and upgrades',()=>{
 it('retains every pickup beyond eight, in its actual color, without rescue top-ups',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));session.start(2);for(const bead of levels[2].beads)session.collect(bead.id);const colors=levels[2].beads.map(b=>b.color);expect(s.data.active!.beads).toEqual(colors);session.rescue();expect(s.data.active!.beads).toEqual(colors);s.data.active!.design=colors.map((_,i)=>i).reverse();session.finishBracelet('My moonstones');expect(s.data.bracelets[0].beads).toEqual([...colors].reverse());expect(validateSave(s.data)).toBe(true);});
 it('zero pickups award zero beads and cannot make an empty bracelet',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));session.start(0);session.rescue();expect(s.data.active!.beads).toEqual([]);expect(()=>session.finishBracelet('Empty')).toThrow();});
 it('rejects nonexistent pickups and out-of-range bead positions',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));session.start(0);expect(session.collect(-1)).toBe(false);session.collect(levels[0].beads[0].id);s.data.active!.design=[99];expect(()=>session.finishBracelet('Bad index')).toThrow();});
 it('migrates old saves without losing old evidence, inventory or story progress',()=>{const s=store(),session=new SessionService(s,new MasteryService(s));session.start(1);const old:any=structuredClone(s.data);old.schemaVersion=1;old.settings.maxSkill='A4';old.completed=[0];old.active.beads=[7,2];old.active.collected=[1,2];old.active.checkpoint=2;for(const id of Object.keys(old.progress))if(!['N0','N1','A1','A2','A3','A4'].includes(id))delete old.progress[id];old.progress.A1.consolidated=true;const upgraded:any=migrateSave(old);expect(validateSave(upgraded)).toBe(true);expect(upgraded.active.beads).toEqual([7,2]);expect(upgraded.completed).toEqual([0]);expect(upgraded.progress.A1.consolidated).toBe(true);expect(upgraded.progress.S6.consolidated).toBe(false);expect(upgraded.settings.maxSkill).toBe('S6');expect(upgraded.active.checkpoint).toBe(0);expect(old.schemaVersion).toBe(1);});
});
