import {describe,test,expect} from 'vitest';
import {catalog,checkAnswer,keypadKeys} from '../src/shared-math/catalog';
import {Skills} from '../src/shared-math/mega-content';
import {Practice,freshMath,validMath,pool,configError} from '../src/shared-math/engine';
import {fresh,migrateSave,validateSave,SaveService} from '../src/core';
import {formatMath} from '../src/math-format';
const targeted=(id='g2-sub',count=1)=>{const s=freshMath();const grade=catalog.find(x=>x.id===id)!.grade;s.config={...s.config,lo:grade,hi:grade,mode:'targeted',selected:[id],count};return s;};
describe('shared catalog',()=>{
 test('imports every one of the 169 reference skills without altering generators',()=>{expect(Skills.list).toHaveLength(169);expect(new Set(catalog.map(x=>x.id)).size).toBe(catalog.length);for(const s of Skills.list)expect(catalog.find(x=>x.id===s.id)?.make).toBe(s.make);for(let g=0;g<=7;g++)expect(catalog.some(x=>x.grade===g)).toBe(true);});
 test('all generators accept their own key and every type has an entry contract',()=>{for(const skill of catalog){for(let i=0;i<100;i++){const q=skill.make();expect(checkAnswer(q,String(q.answer)),skill.id+' '+JSON.stringify(q)).toBe(true);expect(q.prompt.length).toBeGreaterThan(2);expect(formatMath(q.prompt)).not.toContain('<script');expect(keypadKeys(q.type).length).toBeGreaterThanOrEqual(16);}}});
 test('primary arithmetic keys computed independently and bounds hold',()=>{for(const skill of catalog.filter(s=>s.id.startsWith('k-')||s.id.startsWith('g1-')||s.id.startsWith('g2-'))){for(let i=0;i<200;i++){const q=skill.make(),m=q.prompt.match(/^(\d+) ([+−]) (\d+) = \?$/);if(m)expect(q.answer).toBe(m[2]==='+'?Number(m[1])+Number(m[3]):Number(m[1])-Number(m[3]));if(q.type==='number'){expect(Number.isInteger(q.answer)).toBe(true);expect(q.answer).toBeGreaterThanOrEqual(0);expect(q.answer).toBeLessThanOrEqual(skill.grade===0?20:skill.grade===1?120:1000);}}}});
 test('one regrouping is necessary for every new Grade 2 subtraction',()=>{for(let i=0;i<1000;i++){const q=catalog.find(s=>s.id==='g2-sub')!.make();const [a,b]=q.prompt.match(/\d+/g)!.map(Number);expect(a%10).toBeLessThan(b%10);expect(a).toBeGreaterThan(b);expect(a).toBeLessThan(100);expect(q.answer).toBe(a-b);}});
 test('equivalent fractions, negatives, time and algebra preserve the reference response rules',()=>{expect(checkAnswer({prompt:'',answer:'3/2',type:'fraction'},'1 1/2')).toBe(true);expect(checkAnswer({prompt:'',answer:'3/2',type:'fraction'},'6/4')).toBe(false);expect(checkAnswer({prompt:'',answer:'-1/2',type:'fraction'},'−1/2')).toBe(true);expect(checkAnswer({prompt:'',answer:'12:05 PM',type:'time12'},'12:05 pm')).toBe(true);expect(checkAnswer({prompt:'',answer:'3x+6',type:'expanded'},'6+3x')).toBe(true);expect(checkAnswer({prompt:'',answer:'x<3',type:'inequality'},'3>x')).toBe(true);expect(checkAnswer({prompt:'',answer:0,type:'number'},'')).toBe(false);});
 test('fractions and powers render safely with the minus outside',()=>{const html=formatMath('-3/4 + x/2 + 2^3 < 10');expect(html).toContain('-<span class="fraction"');expect(html).toContain('<sup>3</sup>');expect(html).toContain('&lt;');expect(formatMath('<img src=x>')).not.toContain('<img');});
});
describe('settings, progression and gate lifecycle',()=>{
 test('validates ranges, counts and targeted pools; 24-hour skills are opt-in',()=>{const c=freshMath().config;expect(configError({...c,lo:4,hi:2})).toBeTruthy();expect(configError({...c,count:0})).toBeTruthy();expect(configError({...c,selected:[]})).toBeTruthy();const general={...c,mode:'general' as const,lo:0,hi:7};expect(pool(general).some(x=>x.optional24)).toBe(false);expect(pool({...general,include24:true}).some(x=>x.optional24)).toBe(true);});
 test('shuffles without omitting or repeating a skill within one bag',()=>{const s=freshMath();s.config={...s.config,mode:'general',lo:0,hi:0,count:10};const p=new Practice(s),seen=new Set<string>();p.open('practice','a');const length=pool(s.config).length;for(let i=0;i<length;i++){const id=s.gate!.item.skillId;expect(seen.has(id)).toBe(false);seen.add(id);p.next();}expect(seen.size).toBe(length);});
 test('wrong retries preserve question and cannot repair first-attempt evidence',()=>{const s=targeted(),p=new Practice(s);p.open('gate','a');const item=structuredClone(s.gate!.item);expect(p.submit('-999').correct).toBe(false);expect(s.gate!.item).toEqual(item);expect(p.submit(String(item.answer))).toEqual({correct:true,complete:true});expect(s.history['g2-sub']).toEqual([false]);});
 test('settings apply next gate; reload preserves exact question, attempts and count',()=>{const s=targeted('g2-sub',3),p=new Practice(s);p.open('gate','a');p.submit('-1');const before=structuredClone(s.gate);p.saveConfig({...s.config,count:1,selected:['S01']});expect(s.gate).toEqual(before);const restored=structuredClone(s),p2=new Practice(restored);expect(validMath(restored)).toBe(true);p2.open('gate','a');expect(restored.gate).toEqual(before);for(let i=0;i<3;i++)p2.submit(String(restored.gate!.item.answer));p2.open('gate','b');expect(restored.gate!.config.count).toBe(1);expect(restored.gate!.item.skillId).toBe('S01');});
 test('80 percent advances, below 50 steps back, mastery returns to original skill',()=>{const s=targeted(),p=new Practice(s);s.config.mode='progression';s.position='g2-sub';p.open('gate','a');s.gate!.item={...catalog.find(x=>x.id==='g2-sub')!.make(),skillId:'g2-sub'};s.history['g2-sub']=[true,true,true,true,true,true,true,false,false];p.first(true);expect(s.position).not.toBe('g2-sub');s.position='g2-sub';s.history['g2-sub']=[true,true,true,true,false,false,false,false,false];p.first(false);expect(s.position).toBe('g1-sub20');expect(s.returnTo).toEqual(['g2-sub']);p.next();s.history['g1-sub20']=Array(9).fill(true);p.first(true);expect(s.position).toBe('g2-sub');expect(s.returnTo).toEqual([]);});
 test('exact 50 percent stays; no progression outside highest selected grade',()=>{const s=targeted(),p=new Practice(s);s.config.mode='progression';p.open('gate','a');const id=s.gate!.item.skillId;s.history[id]=[true,true,true,true,true,false,false,false,false];s.position=id;p.first(false);expect(s.position).toBe(id);const last=pool(s.config).at(-1)!;s.gate!.item={...last.make(),skillId:last.id};s.position=last.id;s.history[last.id]=Array(9).fill(true);p.first(true);expect(s.position).toBe(last.id);});
 test('old save migration retains rewards and archives without inventing mastery',()=>{const old=fresh();delete old.mathPractice;old.settings.manualSkill='S05';old.completed=[0];old.rescued=['Mochi'];const migrated=migrateSave(old) as ReturnType<typeof fresh>;expect(validateSave(migrated)).toBe(true);expect(migrated.completed).toEqual([0]);expect(migrated.rescued).toEqual(['Mochi']);expect(migrated.mathPractice!.config.selected).toEqual(['S05']);expect(migrated.mathPractice!.history).toEqual({});});
 test('import/export round trip and malformed math state rejection preserve current data',()=>{const service=new SaveService();service.data.mathPractice=targeted();const p=new Practice(service.data.mathPractice);p.open('gate','run');const good=JSON.stringify(service.data);service.import(good);expect(JSON.stringify(service.data)).toBe(good);const bad=JSON.parse(good);bad.mathPractice.config.count=0;expect(()=>service.import(JSON.stringify(bad))).toThrow();expect(JSON.stringify(service.data)).toBe(good);});
 test('skill deletion retains unrelated evidence and rewards',()=>{const s=targeted(),p=new Practice(s);s.history={'g2-sub':[true],'g1-add20':[false]};p.log('answer',{skill:'g2-sub'});p.log('answer',{skill:'g1-add20'});p.resetSkill('g2-sub');expect(s.history).toEqual({'g1-add20':[false]});expect(s.events).toHaveLength(1);});
});
