import {Skills,type MathSkill,type Item} from './mega-content';
import {factBank} from '../facts';
import {expansionSkills} from '../expansion';
import type {SkillId} from '../core';
export type {Item,MathSkill};
const r=(a:number,b:number)=>a+Math.floor(Math.random()*(b-a+1));
const item=(prompt:string,answer:string|number,type='number'):Item=>({prompt,answer,type});
const primary:MathSkill[]=[];
const add=(grade:number,id:string,name:string,make:()=>Item,prereq?:string)=>primary.push({grade,id,name,standard:`${grade===0?'K':grade} text practice`,make,prereq});
const calc=(a:number,op:string,b:number)=>item(`${a} ${op} ${b} = ?`,op==='+'?a+b:a-b);
const compare=(max:number)=>{const a=r(0,max),b=r(0,max);return item(`Compare: ${a} ___ ${b}. Enter <, > or =.`,a<b?'<':a>b?'>':'=','comparison')};
add(0,'k-next','Count forward to 20',()=>{const n=r(0,19);return item(`What number comes after ${n}?`,n+1)});
add(0,'k-before','Count backward within 20',()=>{const n=r(1,20);return item(`What number comes before ${n}?`,n-1)},'k-next');
add(0,'k-sequence','Missing numbers to 20',()=>{const n=r(0,18);return item(`${n}, ___, ${n+2}. What number is missing?`,n+1)},'k-next');
add(0,'k-compare','Compare numbers to 10',()=>compare(10),'k-next');
add(0,'k-add5','Addition within 5',()=>{const a=r(0,5);return calc(a,'+',r(0,5-a))},'k-next');
add(0,'k-sub5','Subtraction within 5',()=>{const a=r(1,5);return calc(a,'−',r(0,a))},'k-add5');
add(0,'k-make10','Make 10',()=>{const n=r(0,10);return item(`${n} + ___ = 10`,10-n)},'k-add5');
add(0,'k-add10','Addition within 10',()=>{const a=r(0,10);return calc(a,'+',r(0,10-a))},'k-add5');
add(0,'k-sub10','Subtraction within 10',()=>{const a=r(1,10);return calc(a,'−',r(0,a))},'k-sub5');
add(0,'k-teen','Teen numbers: ten and ones',()=>{const n=r(1,9);return item(`10 + ${n} = ?`,10+n)},'k-make10');
add(0,'k-stories','Addition and subtraction stories within 10',()=>{const a=r(1,7),b=r(1,3);return r(0,1)?item(`You have ${a} shells. You get ${b} more. How many now?`,a+b):item(`You have ${a+b} shells. You give away ${b}. How many remain?`,a)},'k-sub10');
add(1,'g1-next','Number sequence to 120',()=>{const a=r(20,119);return item(`What number comes after ${a}?`,a+1)},'k-next');
add(1,'g1-place','Tens and ones',()=>{const t=r(1,9),o=r(0,9);return item(`${t} tens and ${o} ones make what number?`,t*10+o)},'k-teen');
add(1,'g1-value','Digit value in two-digit numbers',()=>{const t=r(1,9),o=r(0,9);return item(`In ${t*10+o}, what is the value of the tens digit?`,t*10)},'g1-place');
add(1,'g1-compare','Compare two-digit numbers',()=>compare(99),'k-compare');
add(1,'g1-add20','Addition within 20',()=>{const a=r(1,19);return calc(a,'+',r(1,20-a))},'k-add10');
add(1,'g1-sub20','Subtraction within 20',()=>{const a=r(2,20);return calc(a,'−',r(1,a))},'k-sub10');
add(1,'g1-missing','Missing addition or subtraction numbers',()=>{const a=r(1,10),b=r(1,10);return r(0,1)?item(`${a} + ___ = ${a+b}`,b):item(`___ − ${b} = ${a}`,a+b)},'g1-sub20');
add(1,'g1-equal','Equal expressions',()=>{const a=r(1,9),b=r(1,9),c=r(0,a+b);return item(`${a} + ${b} = ${c} + ___`,a+b-c)},'g1-add20');
add(1,'g1-three','Add three numbers within 20',()=>{const a=r(1,8),b=r(1,8),c=r(1,20-a-b);return item(`${a} + ${b} + ${c} = ?`,a+b+c)},'g1-add20');
add(1,'g1-tens','10 more or 10 less',()=>{const a=r(10,89),up=!!r(0,1);return item(`What is 10 ${up?'more':'less'} than ${a}?`,a+(up?10:-10))},'g1-place');
add(1,'g1-add100','Two-digit addition without regrouping',()=>{const a=r(1,7)*10+r(0,7),b=r(1,9-Math.floor(a/10))*10+r(0,9-a%10);return calc(a,'+',b)},'g1-place');
add(1,'g1-stories','Change and comparison stories within 20',()=>{const a=r(1,10),b=r(1,10);return r(0,1)?item(`Mia has ${a+b} cards. Ben has ${a}. How many more cards does Mia have?`,b):item(`You had some cards. You gave away ${b}. You have ${a} left. How many did you start with?`,a+b)},'g1-missing');
add(1,'g1-time','Hour and half-hour time in words',()=>{const h=r(1,11),half=!!r(0,1);return item(`Write ${half?'half past':'exactly'} ${h} in the morning. Use h:mm AM.`,`${h}:`+(half?'30':'00')+' AM','time12')});
add(2,'g2-place','Hundreds, tens and ones',()=>{const h=r(1,9),t=r(0,9),o=r(0,9);return item(`${h} hundreds + ${t} tens + ${o} ones = ?`,h*100+t*10+o)},'g1-place');
add(2,'g2-compare','Compare numbers to 1000',()=>compare(1000),'g1-compare');
add(2,'g2-skip','Skip count by 2, 5, 10 or 100',()=>{const step=[2,5,10,100][r(0,3)],a=r(0,6)*step;return item(`Count by ${step}: ${a}, ${a+step}, ${a+2*step}, ___.`,a+3*step)},'g1-tens');
add(2,'g2-add','Two-digit addition with regrouping',()=>{const a=r(1,4)*10+r(1,9),b=r(1,4)*10+r(10-a%10,9);return calc(a,'+',b)},'g1-add100');
add(2,'g2-sub','Two-digit subtraction with one regrouping',()=>{const a=r(3,9)*10+r(0,8),b=r(1,Math.floor(a/10)-1)*10+r(a%10+1,9);return calc(a,'−',b)},'g1-sub20');
add(2,'g2-add1000','Addition within 1000',()=>{const a=r(100,800),b=r(10,1000-a);return calc(a,'+',b)},'g2-add');
add(2,'g2-sub1000','Subtraction within 1000',()=>{const a=r(100,999);return calc(a,'−',r(10,a-1))},'g2-sub');
add(2,'g2-mental','Add or subtract 10 or 100',()=>{const n=r(200,800),step=r(0,1)?10:100;return calc(n,r(0,1)?'+':'−',step)},'g1-tens');
add(2,'g2-missing','Missing numbers within 100',()=>{const a=r(10,70),b=r(10,100-a);return r(0,1)?item(`${a+b} − ___ = ${a}`,b):item(`___ + ${b} = ${a+b}`,a)},'g1-missing');
add(2,'g2-stories','Two-step addition and subtraction stories',()=>{const a=r(20,50),b=r(2,20),c=r(2,20);return item(`You have ${a} stickers. You get ${b} more, then give away ${c}. How many remain?`,a+b-c)},'g2-missing');
add(2,'g2-groups','Equal groups by repeated addition',()=>{const a=r(2,5),b=r(2,5);return item(`${a} bags each hold ${b} shells. How many shells altogether?`,a*b)},'g1-three');
add(2,'g2-halves','Half of an even number',()=>{const n=r(1,10);return item(`Share ${n*2} apples equally between 2 people. How many does each person get?`,n)},'g2-groups');
add(2,'g2-money','Coin totals from stated values',()=>{const a=r(1,5),b=r(1,4);return item(`${a} coins are worth 10 cents each. ${b} more coins are worth 5 cents each. How many cents altogether?`,a*10+b*5)},'g2-skip');
add(2,'g2-time','Time to five minutes in words',()=>{const h=r(1,11),m=r(1,11)*5;return item(`Write ${m} minutes after ${h} in the morning. Use h:mm AM.`,`${h}:${String(m).padStart(2,'0')} AM`,'time12')},'g1-time');
const legacyNames:Record<string,string>={N0:'Numbers to 5 (text)',N1:'Compose numbers to 5',A1:'Adding within 5',A2:'Adding 0, 1 and 2',A3:'Doubles within 10',A4:'Making 5 and 10',A5:'Adding to teen numbers',A6:'Adding across 10',A7:'Addition within 20',S1:'Taking away within 5',S2:'Taking away 0, 1 and 2',S3:'Subtraction within 10',S4:'Taking away from teens',S5:'Subtracting across 10',S6:'Subtraction within 20'};
const legacyGrade:Record<string,number>={N0:0,N1:0,A1:0,A2:0,A3:0,A4:0,S1:0,S2:0,S3:0,A5:1,A6:1,A7:1,S4:1,S5:1,S6:1,S01:2,S02:2,S03:2,S04:2,S05:3,S06:3,S07:4,N01:3,N02:4,N03:4,N04:2,N05:2,M01:2,M02:3,M03:3,M04:3,F01:3};
const supplemental:MathSkill[]=[...Object.entries(legacyNames),...expansionSkills.map(([id,name])=>[id,name])].map(([id,name],i,all)=>({id,grade:legacyGrade[id],name:`${name} · Olivia`,standard:'Retained practice',prereq:i?all[i-1][0]:undefined,make:()=>{
 const bank=factBank(id as SkillId),p=bank[r(0,bank.length-1)];
 if(p.kind==='quantity')return item(`0 + ${p.answer} = ?`,p.answer);
 let prompt=[p.story,p.prompt].filter(Boolean).join(' '),answer:string|number=p.answer,type='number';
 if(id==='N03'&&p.choices&&p.prompt.includes('in order')){const values=[p.a,p.b,p.a+20];return item(`Put these numbers in order, smallest first: ${values.join(', ')}. Separate answers with commas; do not use thousands separators.`,values.sort((a,b)=>a-b).join(', '),'sequence');}
 if(p.choices){answer=p.choices[p.answer];type=['<','>','='].includes(String(answer))?'comparison':String(answer).includes('/')?'fraction':'number';prompt+=' Enter your answer.';}
 return item(prompt,answer,type);
}}));
export const catalog:MathSkill[]=[...primary,...supplemental,...Skills.list].sort((a,b)=>a.grade-b.grade);
export const checkAnswer=(q:Item,a:string)=>q.type==='sequence'?a.replace(/\s/g,'')===String(q.answer).replace(/\s/g,''):Skills.check(q,a);
export const gradeLabel=(grade:number)=>grade===0?'K':String(grade);
export function keypadKeys(type:string){const extra=type==='sequence'?[',']:type==='time12'?[':','AM','PM']:type==='time'?[':']:type==='comparison'?['<','>','=']:type==='inequality'?['x','<','>','≤','≥']:['expression','expanded','linear','factored','repeating'].includes(type)?['x','+','×','(',')','^']:[];return ['7','8','9','back','4','5','6','clear','1','2','3','-','0','.','/',' ',...extra];}
