import {test,expect,type Page} from '@playwright/test';
async function solve(page:Page){await expect(page.locator('#submit')).toBeVisible();const p=await page.evaluate(()=> (window as any).__QUEST_DEBUG__.problem);await page.keyboard.press('Delete');await page.keyboard.type(String(p.answer));await page.getByRole('button',{name:'Submit',exact:true}).click();}
// Browser acceptance suite. See the versioned verification record for actual execution evidence.
async function walkTo(page:Page,target:number){
 await page.keyboard.down('ArrowRight');
 for(let step=0;step<550;step++){
  const p=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.player);
  if(p?.x>=target){await page.keyboard.up('ArrowRight');return;}
  const gap=[[400,436],[780,824],[1440,1488]].find(([a,b])=>p&&p.x<b&&a-p.x<=18&&a-p.x>=-3);
  if(gap){await page.keyboard.down('Space');await page.waitForTimeout(780);await page.keyboard.up('Space');}
  else await page.waitForTimeout(80);
 }
 await page.keyboard.up('ArrowRight');throw Error('Could not reach '+target);
}
test('full quest, gate, bracelet, reload and offline',async({page,context})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('button',{name:'Start quest',exact:true})).toBeVisible();await page.screenshot({path:'qa/title.png'});await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();await page.screenshot({path:'qa/math.png'});for(let i=0;i<5;i++)await solve(page);await page.getByRole('button',{name:'Let’s explore!'}).click();await page.waitForTimeout(1200);await page.screenshot({path:'qa/platform.png'});await walkTo(page,1032);await page.getByRole('button',{name:/Open rainbow gate/}).click();for(let i=0;i<5;i++)await solve(page);await walkTo(page,2070);await page.getByRole('button',{name:/Help Mochi/}).click();await expect(page.getByText('A little magic, made by you')).toBeVisible();await page.screenshot({path:'qa/studio.png'});let i=0;while(await page.locator('[data-bead]').count()){await page.locator('[data-bead]').first().click();await page.locator(`[data-index="${i++}"]`).click();}await page.getByRole('button',{name:'Wear my bracelet'}).click();await page.screenshot({path:'qa/ending.png'});await page.getByRole('button',{name:'All done for now'}).click();await page.reload();await page.getByRole('button',{name:'My bracelets'}).click();await expect(page.getByRole('heading',{name:'Meadow Sparkle'})).toBeVisible();await page.getByRole('button',{name:'‹ Home'}).click();await page.evaluate(async()=>await navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Start quest',exact:true})).toBeVisible();expect(errors).toEqual([]);});
test('wrong answer retries without revealing; settings start at the next gate',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();
 const initial=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.problem);await page.keyboard.type('-999');await page.locator('#submit').click();await expect(page.locator('#feedback')).toContainText('Try again');expect(await page.evaluate(()=>(window as any).__QUEST_DEBUG__.problem)).toEqual(initial);
 await page.locator('#math-settings').click();await page.locator('#password').fill('admin123');await page.locator('#unlock').click();await page.locator('#count').fill('1');await page.locator('#save-settings').click();await page.locator('#close-settings').click();expect(await page.evaluate(()=>(window as any).__QUEST_DEBUG__.math.gate.config.count)).toBe(5);await page.reload();await page.getByRole('button',{name:'Continue quest',exact:true}).click();expect(await page.evaluate(()=>(window as any).__QUEST_DEBUG__.problem)).toEqual(initial);await solve(page);
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('olivia-quest-v1')!));expect(state.mathPractice.history.S01[0]).toBe(false);
});
for(const viewport of [{width:852,height:393},{width:1024,height:768},{width:393,height:852}])test(`math layout ${viewport.width}x${viewport.height}`,async({page})=>{
 await page.setViewportSize(viewport);await page.goto('/');await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();await expect(page.locator('#submit')).toBeVisible();const b=await page.locator('#submit').boundingBox();expect(b!.y+b!.height).toBeLessThanOrEqual(viewport.height);expect(b!.x+b!.width).toBeLessThanOrEqual(viewport.width);await page.screenshot({path:`qa/math-${viewport.width}.png`});
});
test('fraction preview and targeted selection on a landscape phone',async({page})=>{
 await page.setViewportSize({width:852,height:393});await page.goto('/');await page.getByRole('button',{name:'Grown-ups',exact:true}).click();await page.locator('#password').fill('admin123');await page.locator('#unlock').click();
 await page.locator('#lo').selectOption('0');await page.locator('#hi').selectOption('7');
 for(const id of await page.locator('#skills input:checked').evaluateAll(xs=>xs.map(x=>(x as HTMLInputElement).value)))await page.locator(`#skills input[value="${id}"]`).uncheck();
 await page.locator('#skill-search').fill('g4-fraction');await page.locator('#skills input[value="g4-fraction"]').check();await page.locator('#diagnostic').click();
 await expect(page.locator('#preview-question .fraction').first()).toBeVisible();await page.locator('#preview-answer').pressSequentially('-3/4');await expect(page.locator('#preview-answer-format .fraction')).toBeVisible();
 const numerator=await page.locator('#preview-answer-format .numerator').boundingBox(),denominator=await page.locator('#preview-answer-format .denominator').boundingBox(),preview=await page.locator('#preview-answer-format').boundingBox();expect(numerator!.y).toBeLessThan(denominator!.y);expect(denominator!.y+denominator!.height).toBeLessThanOrEqual(preview!.y+preview!.height);
 const prompt=await page.locator('#preview-question').boundingBox(),next=await page.locator('#preview-next').boundingBox();expect(prompt!.y).toBeGreaterThanOrEqual(0);expect(next!.y+next!.height).toBeLessThanOrEqual(393);
 await page.screenshot({path:'qa/fraction-phone.png'});await page.locator('#preview-close').click();await expect(page.locator('#mode')).toBeVisible();
});
test('play can pause into settings and return with neutral controls',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();for(let i=0;i<5;i++)await solve(page);await page.getByRole('button',{name:'Let’s explore!'}).click();
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(150);await page.locator('#pause').click();await page.keyboard.up('ArrowRight');await page.locator('#settings').click();await page.locator('#password').fill('admin123');await page.locator('#unlock').click();await page.locator('#close-settings').click();expect(await page.evaluate(()=>(window as any).__QUEST_DEBUG__.mode)).toBe('PlatformScene');await page.waitForTimeout(250);const x=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.player.x);await page.waitForTimeout(250);expect(Math.abs((await page.evaluate(()=>(window as any).__QUEST_DEBUG__.player.x))-x)).toBeLessThan(2);
 const button=page.locator('[data-control="right"]');await button.dispatchEvent('pointerdown',{pointerId:91,pointerType:'touch',buttons:1});await page.dispatchEvent('body','pointercancel',{pointerId:91,pointerType:'touch',buttons:0});expect(await page.evaluate(()=>(window as any).__QUEST_DEBUG__.controls.right)).toBe(false);
});
