import {test,expect,type Page} from '@playwright/test';
async function solve(page:Page){const p=await page.evaluate(()=> (window as any).__QUEST_DEBUG__.problem);for(const n of String(p.answer))await page.getByRole('button',{name:n,exact:true}).click();await page.getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByRole('button',{name:'Keep going',exact:true})).toBeVisible();await page.getByRole('button',{name:'Keep going',exact:true}).click();}
// Authored browser acceptance test; not executed in the restricted build environment.
async function walkTo(page:Page,target:number){
 await page.keyboard.down('ArrowRight');
 for(let step=0;step<550;step++){
  const p=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.player);
  if(p?.x>=target){await page.keyboard.up('ArrowRight');return;}
  const gap=[[400,436],[780,824],[1440,1488]].find(([a,b])=>p&&p.x<b&&a-p.x<=18&&a-p.x>=-3);
  if(gap){await page.keyboard.down('Space');await page.waitForTimeout(780);await page.keyboard.up('Space');}
  else await page.waitForTimeout(80);
 }
 await page.keyboard.up('ArrowRight');throw Error('Could not reach '+target);
}
test('full quest, gate, bracelet, reload and offline',async({page,context})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('button',{name:'Start quest',exact:true})).toBeVisible();await page.screenshot({path:'qa/title.png'});await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();await page.screenshot({path:'qa/math.png'});for(let i=0;i<5;i++)await solve(page);await page.getByRole('button',{name:'Let’s explore!'}).click();await page.waitForTimeout(1200);await page.screenshot({path:'qa/platform.png'});await walkTo(page,1032);await page.getByRole('button',{name:/Open rainbow gate/}).click();await solve(page);await solve(page);await walkTo(page,2070);await page.getByRole('button',{name:/Help Mochi/}).click();await expect(page.getByText('A little magic, made by you')).toBeVisible();await page.screenshot({path:'qa/studio.png'});let i=0;while(await page.locator('[data-bead]').count()){await page.locator('[data-bead]').first().click();await page.locator(`[data-index="${i++}"]`).click();}await page.getByRole('button',{name:'Wear my bracelet'}).click();await page.screenshot({path:'qa/ending.png'});await page.getByRole('button',{name:'All done for now'}).click();await page.reload();await page.getByRole('button',{name:'My bracelets'}).click();await expect(page.getByRole('heading',{name:'Meadow Sparkle'})).toBeVisible();await page.getByRole('button',{name:'‹ Home'}).click();await page.evaluate(async()=>await navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Start quest',exact:true})).toBeVisible();expect(errors).toEqual([]);});
test('wrong answer, meaningful guided steps and touch keypad',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Start quest',exact:true}).click();await page.getByRole('button',{name:'Make some magic'}).click();const initial=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.problem);for(const n of String(initial.answer+1))await page.getByRole('button',{name:n,exact:true}).click();await page.getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByText('Let’s build it together.')).toBeVisible();const p=await page.evaluate(()=>(window as any).__QUEST_DEBUG__.problem);for(let i=0;i<2;i++){for(const n of String(p.answer))await page.getByRole('button',{name:n,exact:true}).click();await page.getByRole('button',{name:'Check',exact:true}).click();}await expect(page.getByText('You built it!')).toBeVisible();const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('olivia-quest-v1')!));expect(data.attempts[0].hint).toBe(true);expect(data.attempts[0].latencyMs).toBeNull();expect(data.active.energy).toBe(2);});
