import {bindHeldControls} from './held-controls';
import {Practice,freshMath} from './shared-math/engine';
import {catalog,keypadKeys} from './shared-math/catalog';
import {settingsHTML,wireSettings} from './shared-math/settings';
import Phaser from 'phaser';
import './style.css';
import {installViewport} from './viewport';
import {VERSION} from './version';
import {levels} from './levels';
import {beadAttributes,beadDecoration} from './beads';
import {numberText} from './expansion';
import {formatMath} from './math-format';
import type {WorldStatus} from './world';
import {quests,beadColors,beadNames,SaveService,MasteryService,SessionService,factEvidence,validateContent,type Attempt} from './core';
import {BootScene,PreloadScene,PlatformScene,screenNames,screenScene,setHooks,controls,clearControls,asset} from './world';
import {AudioService} from './audio';
validateContent();
let storage:Storage|undefined;try{storage=window.localStorage;}catch{}
 if(!storage){const warning=document.createElement('p');warning.textContent='This browser has disabled saving. Export progress in Grown-ups before closing.';warning.className='storage-warning';document.body.appendChild(warning);}
const save=new SaveService(storage),mastery=new MasteryService(save),session=new SessionService(save,mastery),audio=new AudioService();
const ui=document.querySelector<HTMLElement>('#ui')!,touch=document.querySelector<HTMLElement>('#touch')!;
let screenCallback=()=>{},mode='',game:Phaser.Game,offlineReady=false,updateWaiting:ServiceWorker|null=null,parentOpen=false,mathKey:((e:KeyboardEvent)=>void)|null=null;
let mathContext:Attempt['context']='practice',entered='',hiddenAt=0,pauseTime=0;
const escapeHtml=(x:string)=>x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const sprite=(id:number,cls='')=>`<img class="sprite ${cls}" src="${asset(`sprite-${id}.png`)}" alt="">`;
const questSprite=(q:(typeof quests)[number],cls='')=>q.portrait?`<img class="sprite ${cls}" src="${asset(q.portrait)}" alt="">`:sprite(q.mapSprite??q.sprite,cls);
const bead=(id:number,extra='')=>`<span class="bead" ${beadAttributes(id)} ${extra}>${beadDecoration(id)}</span>`;
const btn=(id:string,label:string,cls='')=>`<button id="${id}" class="${cls}">${label}</button>`;
function on(id:string,fn:()=>void){document.getElementById(id)?.addEventListener('click',()=>{audio.unlock();fn();});}
function resetKeyboard(){const scene=game?.scene.getScene('PlatformScene');scene?.input?.keyboard?.resetKeys();}
function applySettings(){Object.assign(audio,{music:save.data.settings.music,sfx:save.data.settings.sfx,readAloud:save.data.settings.readAloud});}
applySettings();
installViewport(()=>{if(game){clearControls();resetKeyboard();game.scale?.refresh();}});
document.title=`Olivia’s Magic Bracelet Quest · v${VERSION}`;
const versionBadge=document.createElement('span');versionBadge.className='version-badge';versionBadge.textContent=`v${VERSION}`;document.querySelector('#app')!.appendChild(versionBadge);
function mount(key:string,html:string,wire:()=>void=()=>{}) {audio.stopVoice();audio.setTheme?.(0);if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=null;clearControls();touch.innerHTML='';mode=key;screenCallback=()=>{ui.innerHTML=html;wire();};game.scene.getScenes(true).forEach(s=>game.scene.stop(s.scene.key));game.scene.start(key);}
function title(){mount('TitleScene',`<div class="screen title-screen"><img class="title-logo" src="${asset('logo.webp')}" alt="Olivia’s Magic Bracelet Quest — A Math Adventure"><div class="title-friends">${sprite(8,'pet')}${sprite(0)}${sprite(7)}${sprite(9,'pet')}</div><div class="title-buttons">${btn('play',save.data.active?'Continue quest':'Start quest','primary')}${btn('map','Adventure map')}${btn('gallery','My bracelets','pink')}</div><p class="footer-note">A little number magic. A big adventure.</p>${save.error?`<p class="error">${escapeHtml(save.error)}</p>`:''}<div class="title-footer"><span id="offline">${location.protocol==='file:'?'Offline edition':offlineReady?'Ready for offline play':'Loading offline adventure…'}</span><span id="hold" class="hold-note"></span>${btn('parent','Grown-ups','small ghost')}</div></div>`,()=>{on('play',()=>{if(save.error){parentChallenge();return;}session.beginSession();if(save.data.active)resume();else{session.start(0);story();}});on('map',map);on('gallery',gallery);on('parent',parentChallenge);});}
function map(){mount('WorldMapScene',`<div class="screen map-screen"><div class="topline">${btn('home','‹ Home','small ghost')}<span class="eyebrow">Beadlight Kingdom</span>${save.data.active?btn('resume','Continue quest','small primary'):'<span></span>'}</div><div class="map-title"><h1>Beadlight Adventures</h1><p class="subtitle">Six different trails. A bracelet from every adventure.</p></div><div class="quest-row">${quests.map(q=>{const unlocked=q.id===0||save.data.completed.includes(q.id-1);return `<article class="quest-card panel" data-theme="${levels[q.id].theme}"><span class="quest-index">${q.id+1}</span>${questSprite(q,unlocked?'':'character-lock')}<h3>${q.name}</h3><p class="subtitle">${q.subtitle}</p><button data-quest="${q.id}" ${unlocked?'':'disabled'} class="${unlocked?'primary':''}">${save.data.completed.includes(q.id)?'Play again':unlocked?'Let’s go':'Help a friend first'}</button></article>`;}).join('')}</div><div class="sanctuary"><strong>Our friends</strong>${save.data.rescued.length?save.data.rescued.map(a=>`${sprite(quests.find(q=>q.animal===a)!.sprite)}<span>${a}</span>`).join(''):'Your first friend is waiting in the meadow.'}</div><p class="footer-note">Replaying an adventure keeps your bracelets and gently grows your math.</p></div>`,()=>{on('home',title);on('resume',resume);document.querySelectorAll<HTMLButtonElement>('[data-quest]').forEach(b=>b.onclick=()=>{audio.unlock();if(save.error){parentChallenge();return;}if(save.data.active&&save.data.active.phase!=='result'){confirmAbandon(Number(b.dataset.quest));return;}session.start(Number(b.dataset.quest));story();});});}
function confirmAbandon(q:number){mount('WorldMapScene',`<div class="screen paused"><div class="panel success-card"><h2>There’s a quest waiting</h2><p>Continue it, or start this adventure? Your saved bracelets and number practice will stay safe.</p>${btn('resume','Continue my quest','primary')}${btn('newq','Start this adventure')}${btn('back','Back','small')}</div></div>`,()=>{on('resume',resume);on('back',map);on('newq',()=>{session.start(q);story();});});}
function resume(){const r=save.data.active;if(!r){map();return;}if(r.phase==='story')story();else if(r.phase==='practice')startMath('practice');else if(r.phase==='gate'){r.phase='platform';save.persist();startPlatform();}else if(r.phase==='platform')startPlatform();else if(r.phase==='studio')studio();else result();}
function story(){const q=quests[save.data.active!.quest];mount('WorldMapScene',`<div class="screen"><div class="panel story">${questSprite(q)}<article><p class="eyebrow">Adventure ${q.id+1}</p><h2>${q.name}</h2><p>${q.story}</p><div class="row">${btn('hear','Listen','small')}${btn('go','Make some magic','primary')}</div>${btn('home','Save & home','small ghost')}</article></div></div>`,()=>{audio.speak(q.story);on('hear',()=>audio.speak(q.story,true));on('home',title);on('go',()=>{save.data.active!.phase='practice';save.persist();startMath('practice');});});}
function startPlatform(){if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=null;audio.stopVoice();clearControls();game.scene.getScenes(true).forEach(s=>game.scene.stop(s.scene.key));ui.innerHTML='';mode='PlatformScene';game.scene.start('PlatformScene');installTouch();}
function hud(context:string,status?:WorldStatus){
 if(mode!=='PlatformScene')return;const r=save.data.active!,flight=status?.flight;
 const progress=flight?`<div class="moon-status flight-status">${flight.flying?flight.progress+'% · To Poppy’s picnic':'Ready at the sky gate'}<span class="flight-progress"><i style="width:${flight.progress}%"></i></span> · ${flight.boostReady?'★ Dash ready':'★ Recharging'}</div>`:`<div class="moon-status ${status?.moonSeconds?'shining':''}">${status?.moonSeconds?'☾ Moon Sight · '+status.moonSeconds+'s · ':''}${escapeHtml(status?.moonHint||'☾ Reveal secret beads')}</div>`;
 ui.innerHTML=`<div class="hud"><div class="hud-pill"><b>${quests[r.quest].name}</b></div>${flight?'':`<div class="hud-pill energy" aria-label="${r.energy} sparkle energy">${'★'.repeat(r.energy)}<span style="opacity:.25">${'★'.repeat(6-r.energy)}</span></div>`}<div class="hud-pill">Beads ${r.beads.length}</div>${btn('pause','Ⅱ','small ghost')}</div>${progress}<div class="carried-beads" aria-label="Your collected beads">${r.beads.map(i=>bead(i)).join('')}</div>${status?.message?`<div class="world-notice">${escapeHtml(status.message)}</div>`:''}${context?btn('interact',context,'context-button'):''}<span class="control-hint">${flight?'↑ / W / Space rise · ↓ / S dive · Q star dash':'Arrows / A D · Space jump · Q star hop · W moon sight'}</span>`;
 on('pause',pause);on('interact',()=>{controls.interact=true;setTimeout(()=>controls.interact=false,120);});
}
let releaseTouch:(()=>void)|undefined;
function installTouch(){
 const flight=levels[save.data.active!.quest].ride;
 touch.innerHTML=flight?`<div class="touch-controls flight-controls ${save.data.settings.leftHanded?'left-handed':''}"><div class="control-cluster"><button class="touch-button power" data-control="up" aria-label="Rise">↑<br>Rise</button><button class="touch-button power" data-control="down" aria-label="Dive">↓<br>Dive</button></div><div class="control-cluster"><button class="touch-button power" data-control="power" aria-label="Star dash">★<br>Star Dash</button></div></div>`:`<div class="touch-controls ${save.data.settings.leftHanded?'left-handed':''}"><div class="control-cluster"><button class="touch-button" data-control="left" aria-label="Move left">◀</button><button class="touch-button" data-control="right" aria-label="Move right">▶</button></div><div class="control-cluster"><button class="touch-button power" data-control="moon" aria-label="Moon sight">☾<br>Moon Sight</button><button class="touch-button power" data-control="power" aria-label="Star hop">★<br>High hop</button><button class="touch-button" data-control="jump" aria-label="Jump">↑</button></div></div>`;
 releaseTouch?.();releaseTouch=bindHeldControls(touch,(key,held)=>{controls[key as keyof typeof controls]=held;if(held)audio.unlock();});
}
function pause(){if(mode!=='PlatformScene')return;releaseTouch?.();clearControls();resetKeyboard();game.scene.pause('PlatformScene');audio.stopVoice();mode='Paused';touch.innerHTML='';ui.innerHTML=`<div class="screen paused"><div class="panel success-card"><h2>A little breather</h2><p>Your adventure is safe.</p>${btn('return','Keep playing','primary')}${btn('controls','How to play')}${btn('settings','Settings')}${btn('home','Save & home','small')}</div></div>`;on('return',resumePlatform);on('settings',()=>openMathSettings('platform'));on('controls',()=>{ui.innerHTML=`<div class="screen paused"><div class="panel success-card walkthrough"><h2>Your adventure kit</h2>${levels[save.data.active!.quest].ride?'<p><strong>Fly:</strong> Lumi moves forward. Hold ↑ / W / Space to rise, ↓ / S to dive. Release to level out.</p><p><strong>Star Dash:</strong> tap ★ or Q for a speed burst. It recharges by itself.</p><p><strong>Bumps:</strong> slow you briefly. Every collected bead stays safe. Math happens only before takeoff.</p>':'<p><strong>Walk and jump:</strong> arrow buttons + ↑, or arrows + Space. Always free.</p><p><strong>Star hop:</strong> ★ or Q. Spend one sparkle for a higher jump.</p><p><strong>Moon sight:</strong> ☾ or W. Light up hidden beads for eight seconds. Follow the glow and arrow.</p><p><strong>Help:</strong> tap the gold message near a gate, well or friend—or press E.</p><p>Walking under high platforms is fine. Collecting extra beads is your choice.</p>'}${btn('return','Ready!','primary')}</div></div>`;on('return',resumePlatform);});on('home',()=>{save.persist();game.scene.stop('PlatformScene');title();});}
function resumePlatform(){audio.stopVoice();clearControls();game.scene.stop('MathOverlayScene');if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=null;mode='PlatformScene';game.scene.resume('PlatformScene');const s=game.scene.getScene('PlatformScene') as PlatformScene;audio.setTheme?.(save.data.active!.quest);if(s.flight)s.flight.report(true);else hud(s.context,s.status);installTouch();}
function practice(){if(!save.data.mathPractice)save.data.mathPractice=freshMath();return new Practice(save.data.mathPractice,()=>{save.persist();});}
let settingsOrigin:'home'|'platform'|'math'='home';
function openMathSettings(origin:'platform'|'math'){settingsOrigin=origin;clearControls();audio.stopVoice();if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=null;parentChallenge();}
function adultScreen(html:string,wire:()=>void){
 if(settingsOrigin!=='home'&&game.scene.isActive('PlatformScene')||settingsOrigin!=='home'&&game.scene.isPaused('PlatformScene')){mode='ParentDashboardScene';ui.innerHTML=html;touch.innerHTML='';wire();}
 else mount('ParentDashboardScene',html,wire);
}
function closeAdult(){parentOpen=false;const origin=settingsOrigin;settingsOrigin='home';if(origin==='platform')resumePlatform();else if(origin==='math')startMath(mathContext);else title();}
function startMath(context:Attempt['context']){releaseTouch?.();resetKeyboard();mathContext=context;const r=save.data.active;if(context!=='parent-check'&&!r)return;if(context==='gate'){r!.phase='gate';save.persist();}if(context==='gate'||context==='refill'){game.scene.pause('PlatformScene');clearControls();touch.innerHTML='';}practice().open(context,context==='parent-check'?'adult':r!.id);renderMath();}
function renderMath(){const g=practice().state.gate;if(!g)return;entered='';const skill=catalog.find(s=>s.id===g.item.skillId)!;
 const label=mathContext==='practice'?'Magic practice':mathContext==='gate'?(levels[save.data.active!.quest].ride?'Sky gate · before takeoff':'Rainbow gate'):mathContext==='refill'?'Sparkle well':'Grown-up practice';
 const keys=keypadKeys(g.item.type),columns=keys.length>20?5:4;
 const html=`<div class="screen shared-gate"><div class="math-head">${btn('save-home','Save & home','small ghost')}<strong>${label}</strong>${btn('math-settings','Settings','small')}</div><div class="panel shared-gate-panel"><div class="gate-reading"><p>${g.completed} / ${g.config.count} completed · ${escapeHtml(skill.name)}</p><div id="question" class="shared-question">${formatMath(g.item.prompt)}</div><p id="feedback" role="status" aria-live="polite"></p>${btn('read','Listen','small')}</div><div class="gate-entry"><input id="answer" readonly inputmode="none" autocomplete="off" aria-label="Answer; use keypad or physical keyboard"><div id="answer-preview" aria-hidden="true"></div><div id="keypad" style="grid-template-columns:repeat(${columns},minmax(0,1fr));grid-template-rows:repeat(${Math.ceil(keys.length/columns)},minmax(30px,1fr))">${keys.map(k=>`<button data-entry="${escapeHtml(k)}" aria-label="${escapeHtml(k===' '?'Space':k==='back'?'Backspace':k)}">${escapeHtml(({back:'⌫',clear:'Clear',' ':'Space','-':'−'} as Record<string,string>)[k]||k)}</button>`).join('')}</div>${btn('submit','Submit','primary')}</div></div></div>`;
 const wire=()=>{on('save-home',()=>{save.persist();title();});on('math-settings',()=>openMathSettings('math'));on('read',()=>audio.speak(g.item.prompt,true));on('submit',respond);
 document.querySelectorAll<HTMLButtonElement>('[data-entry]').forEach(b=>b.onclick=()=>enterAnswer(b.dataset.entry!));
 if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=e=>{if(e.target instanceof HTMLElement&&/SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Enter'){e.preventDefault();respond();}else if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();enterAnswer(e.key==='Backspace'?'back':'clear');}else if(/^[0-9aApPmMxX.,: /+*×÷()^<>≤≥=−-]$/.test(e.key)){e.preventDefault();enterAnswer(e.key);}};window.addEventListener('keydown',mathKey);audio.speak(g.item.prompt);};
 if(mathContext==='gate'||mathContext==='refill'){mode='MathOverlayScene';screenCallback=()=>{ui.innerHTML=html;wire();};if(game.scene.isActive('MathOverlayScene')){ui.innerHTML=html;wire();}else game.scene.start('MathOverlayScene');}else mount('MathStationScene',html,wire);
}
function enterAnswer(key:string){if(key==='back')entered=entered.slice(0,-1);else if(key==='clear')entered='';else if(key==='AM'||key==='PM')entered=entered.replace(/\s*(?:AM|PM)$/i,'').trimEnd()+' '+key;else if(entered.length<80)entered+=key;
 const input=document.getElementById('answer') as HTMLInputElement|null;if(input)input.value=entered;const preview=document.getElementById('answer-preview');if(preview)preview.innerHTML=formatMath(entered);}
function respond(){if(!entered.trim())return;audio.unlock();const result=practice().submit(entered);if(!result.correct){document.getElementById('feedback')!.textContent='Try again. Fractions must be reduced.';return;}
 const r=save.data.active;if(mathContext!=='parent-check'&&r){r.energy=Math.min(6,r.energy+(mathContext==='refill'?2:1));if(mathContext==='practice')r.practiceDone=Math.min(5,r.practiceDone+1);if(mathContext==='gate')r.gateDone=Math.min(2,r.gateDone+1);save.persist();}audio.good();if(result.complete){if(mathKey)window.removeEventListener('keydown',mathKey);mathKey=null;completeMath();}else renderMath();}
function completeMath(){if(mathContext==='parent-check'){dashboard();return;}const r=save.data.active!;if(mathContext==='gate'){r.gateOpen=true;r.phase='platform';save.persist();resumePlatform();return;}if(mathContext==='refill'){resumePlatform();return;}r.phase='platform';save.persist();mount('MathStationScene',`<div class="screen"><div class="panel success-card">${sprite(3)}<h2>Your adventure is ready!</h2><p>${escapeHtml(levels[r.quest].lesson)}</p><p class="note">Every bead you collect is yours to use in the bracelet studio. ${levels[r.quest].ride?'Math comes before takeoff. Enjoy the whole flight without stopping.':'Walking and ordinary jumps are free.'}</p>${btn('adventure',levels[r.quest].ride?'Meet Lumi at the sky gate!':'Let’s explore!','primary')}</div></div>`,()=>on('adventure',startPlatform));}
function studio(){const r=save.data.active!;r.phase='studio';save.persist();let selected:number|null=null;const positions=r.beads.map((_,i)=>({x:50+40*Math.cos(-Math.PI/2+i*2*Math.PI/r.beads.length),y:50+36*Math.sin(-Math.PI/2+i*2*Math.PI/r.beads.length)}));
 mount('BraceletStudioScene',`<div class="screen studio-screen"><div class="topline">${btn('home','Save & home','small ghost')}<span class="eyebrow">The bracelet studio</span>${sprite(7)}</div><h2>A little magic, made by you</h2><p class="subtitle">${r.beads.length} beads collected, ${r.beads.length} beads to create with. Choose beads one by one, or Auto-thread the rest.</p><div class="studio-layout panel"><div class="bracelet-preview" style="--slot-size:${r.beads.length>24?23:r.beads.length>16?28:34}px"><div class="cord"></div><span class="charm-center" id="charm-preview">★</span>${positions.map((p,i)=>`<button class="bracelet-slot" data-index="${i}" style="left:${p.x}%;top:${p.y}%" aria-label="Bracelet slot ${i+1}"></button>`).join('')}</div><div class="studio-controls"><div id="tray" class="bead-tray"></div><div class="row" id="charms"><button data-charm="star" class="small">★ Star</button><button data-charm="heart" class="small">♥ Heart</button><button data-charm="moon" class="small">☾ Moon</button></div><label class="note">Bracelet name<input id="bracelet-name" maxlength="40" value="${['Meadow Sparkle','Forest Friendship','Moonstone Magic','Rainbow Rider','Sunstone Shine','Frostglow Friendship'][r.quest]}"></label><div class="row">${btn('thread','Thread bead','small')}${btn('auto-thread','Auto-thread','small primary')}${btn('undo','Undo','small')}${btn('finish','Wear my bracelet','primary')}${btn('gather','Collect more beads','small')}</div><p id="studio-note" class="note"></p></div></div></div>`,()=>{
 const draw=()=>{document.getElementById('tray')!.innerHTML=r.beads.map((color,i)=>r.design.includes(i)?'':`<button class="bead" data-bead="${i}" draggable="true" aria-label="${beadNames[color]} bead" ${beadAttributes(color)}>${beadDecoration(color)}</button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-bead]').forEach(b=>{b.onclick=()=>{selected=Number(b.dataset.bead);document.querySelectorAll('[data-bead]').forEach(el=>el.classList.remove('selected'));b.classList.add('selected');};b.ondragstart=e=>{selected=Number(b.dataset.bead);e.dataTransfer?.setData('text/plain',String(selected));};});document.querySelectorAll<HTMLButtonElement>('[data-index]').forEach((slot,i)=>{slot.innerHTML=i<r.design.length?bead(r.beads[r.design[i]]):'';slot.setAttribute('aria-label',`Bracelet slot ${i+1}${i<r.design.length?' filled':''}`);});(document.getElementById('auto-thread') as HTMLButtonElement).disabled=!r.beads.length||r.design.length===r.beads.length;(document.getElementById('finish') as HTMLButtonElement).disabled=!r.beads.length||r.design.length<r.beads.length;document.getElementById('studio-note')!.textContent=r.beads.length?`${r.design.length} of ${r.beads.length} collected beads threaded.`:'No beads collected yet. Go back and pick some up for your bracelet.';document.getElementById('charm-preview')!.textContent=r.charm==='star'?'★':r.charm==='moon'?'☾':'♥';document.querySelectorAll<HTMLButtonElement>('[data-charm]').forEach(b=>b.classList.toggle('selected',b.dataset.charm===r.charm));};
 const place=(slotIndex:number)=>{if(selected===null||!Number.isInteger(selected)||selected<0||selected>=r.beads.length||r.design.includes(selected))return;const at=Math.min(slotIndex,r.design.length);r.design.splice(at,0,selected);selected=null;audio.tone(660+at*55,.09);save.persist();draw();};
 document.querySelectorAll<HTMLButtonElement>('[data-index]').forEach(b=>{b.onclick=()=>place(Number(b.dataset.index));b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();const value=e.dataTransfer?.getData('text/plain');if(value!==undefined&&value!=='')selected=Number(value);if(selected!==null&&selected>=0&&selected<r.beads.length)place(Number(b.dataset.index));};});document.querySelectorAll<HTMLButtonElement>('[data-charm]').forEach(b=>b.onclick=()=>{r.charm=b.dataset.charm as typeof r.charm;save.persist();draw();});on('thread',()=>place(r.design.length));on('auto-thread',()=>{session.autoThread();selected=null;audio.tone(784,.16);draw();});on('gather',()=>{r.phase='platform';r.checkpoint=0;r.flight=undefined;save.persist();startPlatform();});on('home',title);on('undo',()=>{r.design.pop();save.persist();draw();});on('finish',()=>{session.finishBracelet((document.getElementById('bracelet-name') as HTMLInputElement).value);audio.good();result();});draw();audio.speak('Let’s make your bracelet! Choose any bead you like.');});}
function result(){const r=save.data.active!,q=quests[r.quest];const due=Date.now()-save.data.session.started>=save.data.settings.sessionMinutes*60000;mount('QuestResultScene',`<div class="screen"><div class="panel success-card">${sprite(q.sprite)}<p class="eyebrow">A friend brought home</p><h2>${q.ending}</h2><div class="mini-bracelet">${save.data.bracelets.find(b=>b.id===r.braceletId)?.beads.map(i=>bead(i)).join('')||''}</div><p>${q.id===0?'Moon Sight reveals secret beads. Look for crescent marks on your next trail.':due?'A lovely place to stop. Your friends will be here next time.':'Your bracelet is saved. There’s always another little adventure.'}</p><div class="row">${btn('map','Adventure map','primary')}${btn('home','All done for now')}</div></div></div>`,()=>{audio.speak(q.ending);const finish=(fn:()=>void)=>{save.data.active=undefined;save.persist();fn();};on('map',()=>finish(map));on('home',()=>finish(title));});}
function gallery(){mount('WorldMapScene',`<div class="screen"><div class="topline">${btn('home','‹ Home','small')}<h2>My bracelets</h2><span></span></div><div class="gallery">${save.data.bracelets.length?save.data.bracelets.map(b=>`<article class="panel"><h3>${escapeHtml(b.name)}</h3><div class="mini-bracelet">${b.beads.map(i=>bead(i)).join('')}</div><p>${b.charm==='star'?'★':b.charm==='moon'?'☾':'♥'}</p><button data-delete-bracelet="${escapeHtml(b.id)}" class="small">Delete bracelet</button><button data-wear="${escapeHtml(b.id)}" class="small ${save.data.worn===b.id?'primary':''}">${save.data.worn===b.id?'Wearing':'Wear'}</button></article>`).join(''):'<div class="panel empty">Your first handmade bracelet is waiting at the end of an adventure.</div>'}</div></div>`,()=>{on('home',title);document.querySelectorAll<HTMLButtonElement>('[data-delete-bracelet]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteBracelet;if(confirm('Delete this one saved bracelet? Export progress first; this cannot be undone here. Other bracelets and rescues stay.')){save.data.bracelets=save.data.bracelets.filter(x=>x.id!==id);if(save.data.worn===id)save.data.worn=undefined;save.persist();gallery();}});document.querySelectorAll<HTMLButtonElement>('[data-wear]').forEach(b=>b.onclick=()=>{save.data.worn=b.dataset.wear;save.persist();gallery();});});}
function parentChallenge(){adultScreen(`<div class="screen paused"><div class="panel success-card"><h2>Adult settings</h2><label>Password <input id="password" type="password" autocomplete="off"></label><p id="adult-message" role="status"></p>${btn('unlock','Unlock','primary')}${btn('close-settings','Close settings','small')}</div></div>`,()=>{on('close-settings',closeAdult);on('unlock',()=>{if((document.getElementById('password') as HTMLInputElement).value==='admin123'){parentOpen=true;dashboard();}else document.getElementById('adult-message')!.textContent='Incorrect password.';});});}
function download(name:string,raw:string){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function factPanel(id:'A7'|'S6'){
 const rows=factEvidence(save.data,id,true),byKey=new Map(rows.map(r=>[r.fact.key,r]));
 const seen=rows.filter(r=>r.attempts.length).length,subtract=id==='S6',op=subtract?'−':'+';
 const cells=Array.from({length:441},(_,i)=>{
  const a=Math.floor(i/21),b=i%21,row=byKey.get(`${a}${op}${b}`);
  if(!row)return '<span class="fact outside" aria-hidden="true"></span>';
  const recent=row.attempts.slice(-10),rate=recent.length?recent.filter(a=>a.firstTryCorrect&&!a.hint&&!a.scaffoldDepth).length/recent.length:0;
  const detail=`${a} ${op} ${b}: ${row.attempts.length} attempts; ${recent.length?Math.round(rate*100)+'% independent success in the last '+recent.length:'not practiced yet'}`;
  return `<span class="fact ${recent.length?rate>=.8?'good':'practice':'none'}" title="${detail}" aria-label="${detail}">${a}${op}${b}</span>`;
 }).join('');
 return `<section class="panel" data-coverage="${id}"><details><summary><b>${subtract?'Subtraction':'Addition'} facts through 20</b> · ${seen} / ${rows.length} practiced</summary><p class="note">Every ordered equation has its own cell. Evidence is combined across skills. ${subtract?'Rows are the starting number; columns are the amount taken away.':'Rows are the first addend; columns are the second addend.'} Green: at least 80% independent success in the last 10 attempts; gold: needs practice; gray: no evidence. Scroll sideways to see the full grid.</p><div class="fact-scroll" tabindex="0" role="region" aria-label="${subtract?'Subtraction':'Addition'} fact grid"><div class="fact-grid">${cells}</div></div></details></section>`;
}
function dashboard(){if(!parentOpen){parentChallenge();return;}const s=save.data,p=practice(),currentGate=p.state.gate;
 adultScreen(`<div class="screen scroll-screen dashboard"><div class="topline"><h2>Adult settings</h2>${btn('close-settings','Close settings','small primary')}</div>${save.error?`<p class="error">${escapeHtml(save.error)}</p>`:''}${settingsHTML(p)}<section class="panel"><h2>Olivia game settings</h2><div class="settings-grid">${[['readAloud','Read aloud'],['reducedMotion','Reduced motion'],['leftHanded','Left-handed controls']].map(([key,label])=>`<label>${label}<input type="checkbox" id="${key}" ${s.settings[key as 'readAloud']?'checked':''}></label>`).join('')}<label>Gentle session reminder<select id="sessionMinutes">${[8,10,15].map(n=>`<option ${s.settings.sessionMinutes===n?'selected':''}>${n}</option>`).join('')}</select></label><label>Music volume<input id="music" type="range" min="0" max="1" step=".05" value="${s.settings.music}"></label><label>Sound effects<input id="sfx" type="range" min="0" max="1" step=".05" value="${s.settings.sfx}"></label></div><p class="note">Math uses text and symbols without counting beads. Your collected bracelet beads stay part of the adventure. Read-aloud depends on the installed device voice.</p></section><section class="panel"><details><summary>Archived Olivia evidence · ${s.attempts.length} attempts</summary><p>Earlier practice used different mastery rules. It does not count toward the new progression system.</p>${s.attempts.slice(-12).reverse().map(a=>`<p>${formatMath(a.story?`${a.story} ${a.prompt}`:a.prompt)} → ${formatMath(a.choices?.[a.answer]??numberText(a.answer))}</p>`).join('')}${factPanel('A7')}${factPanel('S6')}</details></section><section class="panel"><h2>Backup and reset</h2><div class="row">${btn('export','Export progress')}${btn('import','Import progress')}${btn('diagnostic','Try selected settings')}${btn('new-game','New Game')}${btn('reset-all','Reset All Data')}<input type="file" id="import-file" accept=".json,application/json" hidden></div><p id="import-note" role="status"></p><p class="note">New Game restarts the current adventure and keeps math history, settings, bracelets and rescues. Reset All Data clears all game and math progress. Export first. Import/reset keeps one local backup. Password protection is a family-use deterrent, not secure authentication. Default password: admin123.</p>${btn('restore-backup','Restore local backup','small')}${updateWaiting?btn('update','Install downloaded update','small'):''}</section><p>A WILLIAM MCADA PRODUCT · v${VERSION}</p></div>`,()=>{
 on('close-settings',closeAdult);
 wireSettings(p,()=>{mathContext=(currentGate?.context||'practice') as Attempt['context'];if(settingsOrigin==='math'){parentOpen=false;settingsOrigin='home';completeMath();}else{if(currentGate?.context==='gate'&&s.active){s.active.gateOpen=true;s.active.phase='platform';}if(currentGate?.context==='practice'&&s.active)s.active.phase='platform';save.persist();dashboard();}},()=>{const config=structuredClone(p.state.config);s.mathPractice=freshMath();s.mathPractice.config=config;save.persist();dashboard();});
 for(const key of ['readAloud','reducedMotion','leftHanded'] as const)document.getElementById(key)!.addEventListener('change',e=>{s.settings[key]=(e.target as HTMLInputElement).checked;save.persist();applySettings();});
 document.getElementById('sessionMinutes')!.addEventListener('change',e=>{s.settings.sessionMinutes=Number((e.target as HTMLSelectElement).value) as 8|10|15;save.persist();});for(const key of ['music','sfx'] as const)document.getElementById(key)!.addEventListener('input',e=>{s.settings[key]=Number((e.target as HTMLInputElement).value);save.persist();applySettings();});
 on('export',()=>download('Olivia-progress.json',save.error?save.backupRaw():JSON.stringify(s,null,2)));on('import',()=>document.getElementById('import-file')!.click());document.getElementById('import-file')!.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f||!confirm('Replace all current game and math progress with this backup? A local backup of current progress will be kept.'))return;try{save.import(await f.text());settingsOrigin='home';applySettings();dashboard();}catch(e){document.getElementById('import-note')!.textContent=(e as Error).message;}});
 on('diagnostic',()=>{settingsOrigin='home';startMath('parent-check');});
 on('new-game',()=>{if(confirm('Restart this adventure? Collected beads in this unfinished run will be lost. Saved bracelets, rescues, settings and math history stay.')){const q=s.active?.quest||0;s.mathPractice!.gate=null;session.start(q);settingsOrigin='home';parentOpen=false;story();}});
 on('reset-all',()=>{if(confirm(`Delete ${s.bracelets.length} bracelets, ${s.rescued.length} rescues, ${s.attempts.length} archived attempts and ${p.state.events.length} math events, settings and the active quest? Export first. One local backup will be retained.`)){save.reset();settingsOrigin='home';applySettings();dashboard();}});
 on('restore-backup',()=>{const raw=storage?.getItem('olivia-quest-v1-backup');if(!raw){document.getElementById('import-note')!.textContent='No local backup is available.';return;}if(confirm('Replace current progress with the local backup? Current progress will become the backup.')){try{save.import(raw);settingsOrigin='home';applySettings();dashboard();}catch(e){document.getElementById('import-note')!.textContent=(e as Error).message;}}});
 on('update',()=>{if(!updateWaiting)return;save.persist();navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});updateWaiting.postMessage({type:'SKIP_WAITING'});});
 });}
setHooks({save,session,audio,gate:()=>startMath('gate'),refill:()=>startMath('refill'),rescue:()=>{session.rescue();studio();},pause,hud,ready:()=>title(),screen:()=>screenCallback()});
game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:320,height:224,pixelArt:true,roundPixels:true,backgroundColor:'#81d5f1',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{gravity:{x:0,y:520},debug:false}},input:{activePointers:4,keyboard:{capture:[]}},scene:[BootScene,PreloadScene,...screenNames.map(screenScene),PlatformScene],audio:{noAudio:true}});
window.addEventListener('blur',()=>{clearControls();resetKeyboard();if(mode==='PlatformScene')pause();if(mode==='MathStationScene'||mode==='MathOverlayScene')hiddenAt=performance.now();audio.context?.suspend();});window.addEventListener('focus',()=>{if(hiddenAt){pauseTime+=performance.now()-hiddenAt;hiddenAt=0;}if(audio.context)void audio.context.resume();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearControls();if(mode==='PlatformScene')pause();if(!hiddenAt)hiddenAt=performance.now();}else if(hiddenAt){pauseTime+=performance.now()-hiddenAt;hiddenAt=0;}});
if('serviceWorker' in navigator&&location.protocol!=='file:'){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;offlineReady=true;const el=document.getElementById('offline');if(el)el.textContent='Ready for offline play';if(reg.waiting)updateWaiting=reg.waiting;reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)updateWaiting=w;});});}catch{const el=document.getElementById('offline');if(el)el.textContent='Online play · offline setup not ready';}});}
// Read-only diagnostics used by acceptance tests. No reward bypass or answer injection.
Object.defineProperty(window,'__QUEST_DEBUG__',{get:()=>({mode,controls:{...controls},skill:save.data.mathPractice?.gate?.item.skillId,problem:save.data.mathPractice?.gate?.item?{...save.data.mathPractice.gate.item}:null,math:save.data.mathPractice?structuredClone(save.data.mathPractice):null,active:save.data.active?structuredClone(save.data.active):null,attempts:save.data.attempts.length,player:game.scene.isActive('PlatformScene')?{x:(game.scene.getScene('PlatformScene') as PlatformScene).player?.x,y:(game.scene.getScene('PlatformScene') as PlatformScene).player?.y}:null})});

